const error_code_en = {
  "400": "Bad Request",
  "401": "Unauthorized",
  "402": "No action for a long time or log in elsewhere, please login again",
  "403": "No access",
  "404": "Forbidden",
  "500": "Internal Server Error, please contact administrator",
  "503": "Gateway Timeout",
  "sso-auth-400001": "Account already exists",
  "sso-auth-400002": "Account does not exist",
  "sso-auth-400003": "Account is locked",
  "sso-auth-400004": "Account format is invalid",
  "sso-auth-400005": "Password format is invalid",
  "sso-auth-400006": "Incorrect account or password",
  "sso-auth-400007": "Account is locked, please contact administrator",
  "sso-auth-400008": "Verification code expired",
  "sso-auth-400009": "Verification code incorrect",
  "sso-auth-400010": "No action for a long time or log in elsewhere, please login again",
  "sso-auth-400011": "refreshToken expired",
  "sso-auth-400012": "Too frequent operation",
  "sso-auth-400013": "Token parameter error",
  "sso-auth-400014": "Password expired, please contact administrator",
  "sso-auth-400015": "Account has been logged in elsewhere, please login agains",
  "sso-auth-400019": "Verification code incorrect",
  "user-auth-400001": "Account does not exist",
  "user-auth-400002": "Account is locked, please contact administrator",
  "user-auth-400003": "Incorrect account or password",
  "user-auth-400004": "Account is locked, please contact administrator",
  "user-auth-400005": "Too frequent operation",
  "user-auth-400006": "Please enter account in email format",
  "user-auth-400007": "Not compliant with password policy",
  "user-account-400001": "Account does not exist",
  "user-account-400002": "Account format is invalid",
  "user-account-400003": "Password format is invalid",
  "user-account-400004": "Password not same",
  "user-account-400005": "Not compliant with password policy",
  "user-account-400006": "Verification code format is invalid",
  "user-account-400007": "Verification code is invalid",
  "user-account-400008": "New password cannot be the same as old password",
  "user-account-400009": "Old password is wrong",
  "user-account-400010": "Operation is too frequent, account is locked! Please contact administrator",
  "user-account-400011": "Account is locked",
}
export default error_code_en